---

- name: provision puppetmaster in EC2
  local_action:
    module: ec2
    state: present
    group: PuppetMasterSecurityGroup
    id: "{{ version }}-master"
    keypair: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami_id }}"
    wait: true
    region: "{{ region }}"
    count: 1
  register: puppetmaster

- name: add puppetmaster to hostgroup
  local_action:
    module: add_host
    hostname: "{{ item.public_ip }}"
    groupname: puppetmaster
  with_items: puppetmaster.instances


- name: create the puppet client config
  local_action:
    module: template
    src: puppet.conf.j2
    dest: ./roles/base/files/puppet.conf
  with_items: puppetmaster.instances

- name: provision puppetclients in EC2
  local_action:
    module: ec2
    state: present
    group: PuppetClientSecurityGroup
    id: "{{ version }}-client"
    keypair: "{{ keypair }}"
    instance_type: "{{ instance_type }}"
    image: "{{ ami_id }}"
    wait: true
    region: "{{ region }}"
    count: 2
  register: puppetclient

- name: add puppetclients to hostgroup
  local_action:
    module: add_host
    hostname: "{{ item.public_ip }}"
    groupname: puppetclient
  with_items: puppetclient.instances

- name: wait for SSH to come up
  local_action:
    module: wait_for
    host: "{{ item.public_ip }}"
    port: 22
    delay: 10
    timeout: 320
    state: started
  with_items: puppetclient.instances