---

- name: Create EC2 infrastructure
  hosts: local
  gather_facts: no
  vars:
    region: us-west-1
    version: 2014060908
    keypair: mbajor-mbpr
    instance_type: t1.micro
    ami_id: ami-a26265e7
    vpc_id: vpc-70676f12
  roles:
    - ec2

- name: Configure the puppetmaster
  hosts: puppetmaster
  user: ubuntu
  roles:
    - base
    - puppet_master


- name: Configure the puppetclient
  hosts: puppetclient
  user: ubuntu
  roles:
    - base